name: fintrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More standard range

dependencies:
  flutter:
    sdk: flutter

  # Firebase Plugins
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.2
  cloud_firestore: ^5.6.6

  # Android Lifecycle Plugin
  flutter_plugin_android_lifecycle: ^2.0.27

  # File Management
  open_file: ^3.5.10
  path_provider: ^2.1.5

  # Local Authentication
  local_auth: ^2.3.0

  # Notifications

  # UI and Utils
  cupertino_icons: ^1.0.8
  fl_chart: ^0.70.2
  intl: ^0.20.2
  pdf: ^3.11.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
