name: fintrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # More standard range

dependencies:
  flutter:
    sdk: flutter

  # Firebase Plugins
  firebase_core: ^2.15.1
  firebase_auth: ^4.7.3
  cloud_firestore: ^4.8.5

  # Android Lifecycle Plugin
  flutter_plugin_android_lifecycle: ^2.0.15

  # File Management
  open_file: ^3.3.2
  path_provider: ^2.1.1

  # Local Authentication
  local_auth: ^2.1.6

  # Notifications
  flutter_local_notifications: ^15.1.1
  timezone: ^0.9.2

  # UI and Utils
  cupertino_icons: ^1.0.5
  fl_chart: ^0.63.0
  intl: ^0.18.1
  pdf: ^3.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.3


dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0

flutter:
  uses-material-design: true
