name: fintrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.1.0+1

environment:
  sdk: ^3.5.1

dependencies:
  flutter:
    sdk: flutter

  # Firebase Plugins
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5

  # Android Lifecycle Plugin (Only if necessary, most dependencies include this already)
  flutter_plugin_android_lifecycle: ^2.0.26

  # File Management
  open_file: ^3.5.4
  path_provider: ^2.1.2

  # Local Authentication
  local_auth: ^2.2.0

  # Notifications
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.2

  # UI and Utils
  cupertino_icons: ^1.0.8
  fl_chart: ^0.66.0
  intl: ^0.18.1
  pdf: ^3.10.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
